---
apiVersion: v1
kind: Secret
metadata:
  name: pullsecret-{{ cluster.name }}
  namespace: {{ cluster.name }}
  labels:
    agent-install.openshift.io/watch: "true"
    cluster.open-cluster-management.io/backup: "true"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{{load_file(account.pullSecret)}}'
