---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: {{ cluster.name }}
  namespace: {{ cluster.name }}
spec:
  applicationManager:
    argocdCluster: false
    enabled: true
  certPolicyController:
    enabled: true
  clusterLabels:
    name: {{ cluster.name }}
    cloud: Baremetal
    vendor: OpenShift
  clusterName: {{ cluster.name }}
  clusterNamespace: {{ cluster.name }}
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
