apiVersion: controlplane.cluster.x-k8s.io/v1alpha2
kind: OpenshiftAssistedControlPlane
metadata:
  name: adobecluster
  namespace: adobe
  annotations: {}
    #cluster.x-k8s.io/release-image-repository-override: registry.ci.openshift.org/ocp/release
spec:
  openshiftAssistedConfigSpec:
    pullSecretRef:
      name: "pull-secret"
    sshAuthorizedKey: "ssh-rsa AAAAB3Nza..."
    nodeRegistration:
      kubeletExtraLabels:
        - 'metal3.io/uuid="${METADATA_UUID}"'
    nmStateConfigLabelSelector: 
      matchLabels:
        role: controller
  distributionVersion: 4.19.10
  config:
    apiVIPs:
    - 172.21.0.201
    ingressVIPs:
    - 172.21.0.200
    baseDomain: openinfra.lab
    pullSecretRef:
      name: "pull-secret"
    sshAuthorizedKey: "ssh-rsa AAAAB3Nza..."
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: Metal3MachineTemplate
      name: adobecluster-master
      namespace: adobe
  replicas: 3
